* What's going on in my life.
- I've just moved to a new country. That's huge even if I don't realize this yet.
- I don't have a job and I feel *bad* about this. Helpless. Sliding into abyss. Oh, and I have a bank loan so I really have to up and start working already.
- I have three kids whom I mostly like and two wonderful partners whom I adore. That's a pretty large family. We might keep each other afloat.
- I have a bunch of disparate interests but no habit of grit. I don't have a 'default' fulfilling activity. I don't really have a clear idea of what fulfills me and what doesn't.
- I have had a vague plan year ago, but I haven't revisited is since.
- I tend to overextend myself and not get anything done.
- I tend to become anxious and afraid of people. This really gets in the way of pursuing social and professional opportunities.

I /wish/ to get a stable job. Working with code and math and smart people. I would like to live alone, close to my kids and partners, spend a lot of time with them, and pursue my various intellectual interests in the little spare time I have left. Poetry. Abstract mathematics. Music. Performance art. A lot of sex with people I deeply respect and love would also be nice.

What I've got instead: I'm unclear on how to even approach getting a job.
Let me outline some plans, write down my expectations, then execute on them and see how it goes.

I spend a lot of time with my computer and become sad, tense and detached.

alright. Walk.
* How to get a job.
** Sit underneath Azrieli towers with a sign "Will formally (dis-)prove correctness of your code for food" 
 - set up a website and link to it.
 - make T-shirts

  "Formal proof of correctness is not only tedious, time-consuming, and outlandishly expensive, it's also not necessarily effective!"
  -- C2 wiki.

** Write a nice post on Mokum

** Contact Maya Geller.

* Think about things that I want to keep track of with Beeminder or Complice. 

** Practice

*** Mindfulness

*** Playing music

*** Code

*** Grammar

*** Communicating with people

** Regimen

*** Sports: do a quick warm-up in the morning.


