I'm a new ole. I've just arrived here at the Ides of March and I'm eager for a human connection. Professional, sexual, intellectual, most of all I just want to delve into the social fabric of the city. 

I have to say upfront that I'm poly. I have two commited partners and three children with one of them. By now I'm pretty certain that polyamory fits in with my worldview and my sense of how I relate to other people. I understand that it's not everyone's cup of tea. 


* Removed <2017-03-21 Tue 00:57>

Feeding the world to math, bit by bit.

I'm polyamorous and I have steady partners who I'm committed to. They're wicked smart and all-around awesome and yes, I might introduce you. I have kids with one of them. Now that should repel 98% of the dating pool so we might get down to business.

I have just moved to Israel and I don't have a steady job here yet. I'm flailing around trying to figure out how the things are done here. Still with me? Alright then.

I love books. And math. And people. Seriously, people are awesome. They're beautiful and resilient and they come up with all sorts of ingenious stuff. I like *making* books and math and, uh, people, I guess. Sometimes it feels as if my life so far have been a weird acid trip through the literary landscape. Once I've found myself in a library of middle-eastern curiosa with hundreds of volumes of cuneiform texts with transcriptions and comments. That felt like striking gold. Whole worlds, unspoilt by the developments of the following millennia.
